import { RiskLevel } from "./navigator-config";

export type SolutionType = {
  id: string;
  name: string;
  yieldLow: number;
  yieldHigh: number;
  minMonths: number;
  risk: string;
  liquidity: string;
  note: string;
};

export const solutionTypes: SolutionType[] = [
  {
    id: "money-market",
    name: "Geldmarktfonds",
    yieldLow: 2.1,
    yieldHigh: 2.8,
    minMonths: 12,
    risk: "niedrig",
    liquidity: "grundsätzlich börsentäglich",
    note: "Kurzfristiger Liquiditätsbaustein; Ertrag folgt dem Geldmarktniveau und ist nicht garantiert.",
  },
  {
    id: "certificates",
    name: "Zertifikate",
    yieldLow: 4.0,
    yieldHigh: 5.5,
    minMonths: 18,
    risk: "produktabhängig",
    liquidity: "laufzeit- und marktpreisabhängig",
    note: "Rendite und Risiko hängen von Basiswert, Barriere, Emittent und Auszahlungsprofil ab.",
  },
  {
    id: "target-2029",
    name: "Rentenlaufzeitfonds 2029",
    yieldLow: 2.3,
    yieldHigh: 3.9,
    minMonths: 36,
    risk: "niedrig bis moderat",
    liquidity: "börsentäglich, Zielhorizont beachten",
    note: "Fälligkeitsorientierte Rentenlösung; Kredit- und Zinsänderungsrisiken bleiben bestehen.",
  },
  {
    id: "defensive-mixed",
    name: "Defensive Mischfonds",
    yieldLow: 3.5,
    yieldHigh: 4.5,
    minMonths: 36,
    risk: "moderat",
    liquidity: "börsentäglich",
    note: "Breiter Baustein mit begrenztem Aktienanteil; zwischenzeitliche Verluste sind möglich.",
  },
  {
    id: "target-2031",
    name: "Rentenlaufzeitfonds 2031",
    yieldLow: 2.7,
    yieldHigh: 4.2,
    minMonths: 48,
    risk: "niedrig bis moderat",
    liquidity: "börsentäglich, Zielhorizont beachten",
    note: "Längere Fälligkeit mit höherem Zinsänderungs- und Kreditrisiko als kurze Laufzeiten.",
  },
  {
    id: "mixed",
    name: "Ausgewogene / offensive Mischfonds",
    yieldLow: 4.0,
    yieldHigh: 7.0,
    minMonths: 48,
    risk: "moderat bis erhöht",
    liquidity: "börsentäglich",
    note: "Aktien- und Rentenquoten variieren; die Bandbreite ist keine belastbare Einzelproduktprognose.",
  },
  {
    id: "global-equity",
    name: "Weltweite Aktienfonds",
    yieldLow: 6.0,
    yieldHigh: 9.0,
    minMonths: 72,
    risk: "erhöht",
    liquidity: "börsentäglich",
    note: "Langfristiger Wachstumsbaustein mit deutlichen Schwankungs- und Verlustrisiken.",
  },
];

export type HouseProduct = {
  id: string;
  name: string;
  wkn: string;
  category: string;
  risk: number;
  horizon: string;
  region: string;
  sustainable: boolean;
  role: "Core" | "Satellit";
  solutionId: string;
  assetMix: AssetMix | null;
};

export const assetClasses = [
  "Liquidität",
  "Geldwerte",
  "Substanzwerte",
  "Alternative Anlagen",
  "Sachwerte",
] as const;
export type AssetClass = (typeof assetClasses)[number];
export type AssetMix = Record<AssetClass, number>;

const mix = (
  liquidity = 0,
  money = 0,
  substance = 0,
  alternatives = 0,
  real = 0,
): AssetMix => ({
  Liquidität: liquidity,
  Geldwerte: money,
  Substanzwerte: substance,
  "Alternative Anlagen": alternatives,
  Sachwerte: real,
});

const mixedSplits: Record<string, AssetMix> = {
  "urak-konservativ": mix(0, 65, 35),
  "urak-esg": mix(0, 35, 65),
  "privatfonds-kontrolliert": mix(0, 35, 60, 5),
  "privatfonds-esg": mix(0, 67, 30, 3),
  uniausschuettung: mix(0, 50, 50),
  "fvs-multi": mix(0, 25, 60, 15),
  fairworld: mix(0, 70, 30),
  blockchain: mix(0, 10, 82.5, 7.5),
  assenagon: mix(0, 50, 50),
  "jpm-income": mix(0, 50, 50),
  "fvs-foundation-r": mix(0, 65, 35),
  "fvs-foundation-sr": mix(0, 50, 50),
  "institutional-balance": mix(0, 80, 20),
  kommunalfonds: mix(0, 75, 25),
  "multi-asset-fk": mix(0, 60, 30, 10),
  stiftungsfonds: mix(0, 65, 35),
};

const productMix = (id: string, category: string): AssetMix | null => {
  if (mixedSplits[id]) return mixedSplits[id];
  if (category === "Aktienfonds") return mix(0, 0, 100);
  if (category === "Rentenfonds" || category === "Geldmarkt")
    return mix(0, 100);
  if (category === "Immobilienfonds") return mix(0, 0, 0, 0, 100);
  if (category === "Alternative Anlagen") return mix(0, 0, 0, 100);
  // Für die beiden zusätzlichen Modellbausteine ZinsFix Index und MEA Einzelwert
  // liefert die Fonds-Matrix keine fachlich freigegebene Durchschau.
  return null;
};

const p = (
  id: string,
  name: string,
  wkn: string,
  category: string,
  risk: number,
  horizon: string,
  region: string,
  sustainable: boolean,
  role: "Core" | "Satellit",
  solutionId: string,
): HouseProduct => ({
  id,
  name,
  wkn,
  category,
  risk,
  horizon,
  region,
  sustainable,
  role,
  solutionId,
  assetMix: productMix(id, category),
});

export const houseProducts: HouseProduct[] = [
  p(
    "uniglobal-net",
    "UniGlobal -net-",
    "975027",
    "Aktienfonds",
    3,
    ">5",
    "Weltweit",
    false,
    "Core",
    "global-equity",
  ),
  p(
    "uniglobal",
    "UniGlobal",
    "849105",
    "Aktienfonds",
    3,
    ">5",
    "Weltweit",
    false,
    "Core",
    "global-equity",
  ),
  p(
    "unifavorit",
    "UniFavorit: Aktien -net-",
    "800751",
    "Aktienfonds",
    3,
    ">5",
    "Weltweit",
    false,
    "Core",
    "global-equity",
  ),
  p(
    "uniesg-global-net",
    "UniESG Aktien Global -net-",
    "A2N7V2",
    "Aktienfonds",
    3,
    ">5",
    "Weltweit",
    true,
    "Core",
    "global-equity",
  ),
  p(
    "uniesg-global",
    "UniESG Aktien Global",
    "A0M80G",
    "Aktienfonds",
    3,
    ">5",
    "Weltweit",
    true,
    "Core",
    "global-equity",
  ),
  p(
    "marktführer",
    "UniMarktführer -net- A",
    "926156",
    "Aktienfonds",
    3,
    ">5",
    "Weltweit",
    false,
    "Core",
    "global-equity",
  ),
  p(
    "dividendenass",
    "UniDividendenAss -net- A",
    "A0B821",
    "Aktienfonds",
    3,
    ">5",
    "Europa",
    false,
    "Core",
    "global-equity",
  ),
  p(
    "uninordamerika",
    "UniNordamerika",
    "975007",
    "Aktienfonds",
    3,
    ">5",
    "USA",
    false,
    "Core",
    "global-equity",
  ),
  p(
    "premium-a",
    "VOBA PUR PREMIUM A UI P",
    "A0M8WZ",
    "Aktienfonds",
    2,
    ">5",
    "Weltweit",
    false,
    "Core",
    "global-equity",
  ),
  p(
    "jpm-europe-value",
    "JPM Europe Strategic Value AAEO",
    "A0DQH5",
    "Aktienfonds",
    3,
    "<5",
    "Europa",
    true,
    "Core",
    "global-equity",
  ),
  p(
    "jpm-dividend",
    "JPMorgan Global Dividend A (EUR dis.)",
    "A1JQFE",
    "Aktienfonds",
    3,
    "<5",
    "Weltweit",
    true,
    "Core",
    "global-equity",
  ),
  p(
    "fidelity-tech",
    "Fidelity Global Technology A (EUR)",
    "921800",
    "Aktienfonds",
    3,
    "<5",
    "Weltweit",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "kbi-infra",
    "KBI Global Sustainable Infrastructure",
    "A2PNM0",
    "Aktienfonds",
    3,
    "<5",
    "Weltweit",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "oekoworld-klima",
    "ÖkoWorld Klima C",
    "A0MX8G",
    "Aktienfonds",
    3,
    ">5",
    "Weltweit",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "nomura-india",
    "Nomura India Equity A (EUR)",
    "A1C9ED",
    "Aktienfonds",
    3,
    "<5",
    "Asien",
    false,
    "Satellit",
    "global-equity",
  ),
  p(
    "pictet-water",
    "Pictet – Water P (EUR)",
    "933349",
    "Aktienfonds",
    3,
    "<5",
    "Weltweit",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "industrie40",
    "UniIndustrie 4.0 -net- A",
    "A3CT9T",
    "Aktienfonds",
    3,
    ">5",
    "Weltweit",
    false,
    "Satellit",
    "global-equity",
  ),
  p(
    "thematica",
    "AGIF Thematica -A- EUR",
    "A2AQF1",
    "Aktienfonds",
    3,
    "<5",
    "Weltweit",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "bellevue",
    "Bellevue Medtech & Services B",
    "A0RP23",
    "Aktienfonds",
    3,
    "<5",
    "Weltweit",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "dws-de",
    "DWS Aktien Strategie Deutschland LC",
    "976986",
    "Aktienfonds",
    3,
    "<5",
    "Deutschland",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "china",
    "Invesco Greater China Equity",
    "973792",
    "Aktienfonds",
    4,
    "<5",
    "Asien",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "asia-pacific",
    "Fidelity Asia Pacific Opportunities",
    "A0NFGE",
    "Aktienfonds",
    3,
    "<5",
    "Asien",
    false,
    "Satellit",
    "global-equity",
  ),
  p(
    "msci-world",
    "iShares Core MSCI World UCITS ETF",
    "A0RPWH",
    "Aktienfonds",
    3,
    "<5",
    "Weltweit",
    false,
    "Core",
    "global-equity",
  ),
  p(
    "sp500",
    "iShares Core S&P 500 UCITS ETF USD (Acc)",
    "A0YEDG",
    "Aktienfonds",
    3,
    "<5",
    "USA",
    false,
    "Core",
    "global-equity",
  ),
  p(
    "eurostoxx",
    "Amundi EURO STOXX 50 II UCITS ETF Acc",
    "798328",
    "Aktienfonds",
    3,
    "<5",
    "Europa",
    true,
    "Core",
    "global-equity",
  ),
  p(
    "dax",
    "iShares Core DAX UCITS ETF (DE) EUR (Acc)",
    "593393",
    "Aktienfonds",
    3,
    "<5",
    "Deutschland",
    false,
    "Satellit",
    "global-equity",
  ),
  p(
    "nasdaq",
    "iShares Nasdaq-100 UCITS ETF USD (Acc)",
    "A0YEDL",
    "Aktienfonds",
    3,
    "<5",
    "USA",
    false,
    "Satellit",
    "global-equity",
  ),
  p(
    "allianz-ai",
    "Allianz Global Artificial Intelligence A EUR",
    "A2DKAR",
    "Aktienfonds",
    4,
    "<5",
    "Weltweit",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "healthscience",
    "BGF World Healthscience A2",
    "A0BL36",
    "Aktienfonds",
    3,
    "<5",
    "Weltweit",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "microcap",
    "Mandarine Europe Microcap R EUR",
    "A2AQ7L",
    "Aktienfonds",
    3,
    "<5",
    "Europa",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "robotics",
    "Pictet - Robotics P dy EUR",
    "A141RC",
    "Aktienfonds",
    4,
    "<5",
    "Weltweit",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "robeco-asia",
    "Robeco Asia-Pacific Equities D EUR",
    "988149",
    "Aktienfonds",
    3,
    "<5",
    "Asien",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "smart-power",
    "TBF SMART POWER EUR R",
    "A0RHHC",
    "Aktienfonds",
    3,
    "<5",
    "Weltweit",
    true,
    "Satellit",
    "global-equity",
  ),
  p(
    "uniem",
    "UniEM Global A",
    "502347",
    "Aktienfonds",
    4,
    ">5",
    "Asien",
    false,
    "Satellit",
    "global-equity",
  ),

  p(
    "urak-konservativ",
    "UniRak ESG Konservativ -net- A",
    "A2DMWZ",
    "Mischfonds",
    2,
    "<5",
    "Weltweit",
    true,
    "Core",
    "defensive-mixed",
  ),
  p(
    "urak-esg",
    "UniRak ESG -net- A",
    "A1JQ11",
    "Mischfonds",
    3,
    "<5",
    "Weltweit",
    true,
    "Core",
    "mixed",
  ),
  p(
    "privatfonds-kontrolliert",
    "PrivatFonds: Kontrolliert pro",
    "A0RPAN",
    "Mischfonds",
    3,
    "<5",
    "Weltweit",
    false,
    "Core",
    "mixed",
  ),
  p(
    "privatfonds-esg",
    "PrivatFonds: ESG",
    "A2N73W",
    "Mischfonds",
    2,
    "<5",
    "Weltweit",
    true,
    "Core",
    "defensive-mixed",
  ),
  p(
    "uniausschuettung",
    "UniAusschüttung -net- A",
    "A2AGK5",
    "Mischfonds",
    3,
    "<5",
    "Weltweit",
    false,
    "Core",
    "mixed",
  ),
  p(
    "fvs-multi",
    "FvS Multi Opportunities R",
    "A0M430",
    "Mischfonds",
    3,
    "<5",
    "Weltweit",
    true,
    "Core",
    "mixed",
  ),
  p(
    "fairworld",
    "FairWorldFonds",
    "A0YCZ3",
    "Mischfonds",
    2,
    "<3",
    "Weltweit",
    true,
    "Core",
    "defensive-mixed",
  ),
  p(
    "blockchain",
    "UniThemen Blockchain",
    "A3CU5D",
    "Mischfonds",
    4,
    ">5",
    "Weltweit",
    false,
    "Satellit",
    "mixed",
  ),
  p(
    "assenagon",
    "Assenagon I Multi Asset Conservativ P EUR",
    "A140LW",
    "Mischfonds",
    2,
    "<5",
    "Weltweit",
    true,
    "Core",
    "defensive-mixed",
  ),
  p(
    "jpm-income",
    "JPM Global Income A (div) EUR",
    "A0RBX2",
    "Mischfonds",
    3,
    "<5",
    "Weltweit",
    false,
    "Core",
    "mixed",
  ),
  p(
    "fvs-foundation-r",
    "FvS Foundation Defensive R",
    "A2QFWV",
    "Mischfonds",
    2,
    "<5",
    "Weltweit",
    true,
    "Core",
    "defensive-mixed",
  ),
  p(
    "fvs-foundation-sr",
    "FvS Foundation Defensive SR",
    "A2AQ5Y",
    "Mischfonds",
    2,
    "<5",
    "Weltweit",
    true,
    "Core",
    "defensive-mixed",
  ),
  p(
    "institutional-balance",
    "UniInstitutional Asset Balance",
    "A0M80K",
    "Mischfonds",
    2,
    "<3",
    "Weltweit",
    true,
    "Core",
    "defensive-mixed",
  ),
  p(
    "kommunalfonds",
    "UniInstitutional Kommunalfonds ESG",
    "A2H9AZ",
    "Mischfonds",
    2,
    "<5",
    "Weltweit",
    true,
    "Core",
    "defensive-mixed",
  ),
  p(
    "multi-asset-fk",
    "UniInstitutional Multi Asset FK",
    "A2H872",
    "Mischfonds",
    3,
    "<5",
    "Weltweit",
    true,
    "Core",
    "mixed",
  ),
  p(
    "stiftungsfonds",
    "UniInstitutional Stiftungsfonds ESG",
    "A2DMVH",
    "Mischfonds",
    2,
    "<5",
    "Weltweit",
    true,
    "Core",
    "defensive-mixed",
  ),

  p(
    "uer-2032",
    "UER Unternehmensanleihen 2032 -net- A",
    "A41CYA",
    "Rentenfonds",
    2,
    ">5",
    "Weltweit",
    false,
    "Core",
    "target-2031",
  ),
  p(
    "uer-2029",
    "UER Unternehmensanleihen 2029 III -net- A",
    "A41CY9",
    "Rentenfonds",
    2,
    "<3",
    "Weltweit",
    false,
    "Core",
    "target-2029",
  ),
  p(
    "carmignac-2031",
    "Carmignac Credit 2031",
    "A40Y9P",
    "Rentenfonds",
    2,
    "<5",
    "Weltweit",
    false,
    "Core",
    "target-2031",
  ),
  p(
    "carmignac-2029",
    "Carmignac Credit 2029",
    "A3EXFX",
    "Rentenfonds",
    2,
    "<5",
    "Weltweit",
    false,
    "Core",
    "target-2029",
  ),
  p(
    "premium-r",
    "VOBA PUR PREMIUM R UI P",
    "A0M8WY",
    "Rentenfonds",
    2,
    "<5",
    "Weltweit",
    false,
    "Core",
    "target-2031",
  ),
  p(
    "uer-corporates",
    "UER Corporates A",
    "940637",
    "Rentenfonds",
    2,
    "<5",
    "Weltweit",
    false,
    "Core",
    "target-2031",
  ),
  p(
    "eurokapital",
    "UniEuroKapital Corporates -net- A",
    "136704",
    "Rentenfonds",
    2,
    "<3",
    "Weltweit",
    false,
    "Core",
    "target-2029",
  ),
  p(
    "acatis-renten",
    "ACATIS IfK Value Renten A",
    "A0X758",
    "Rentenfonds",
    2,
    "<5",
    "Weltweit",
    false,
    "Core",
    "target-2031",
  ),
  p(
    "esg-unternehmensanleihen",
    "UniESG Unternehmensanleihen -net-A",
    "A2P1X8",
    "Rentenfonds",
    2,
    "<5",
    "Weltweit",
    true,
    "Core",
    "target-2031",
  ),
  p(
    "unieuro-renta",
    "UniEuroRenta",
    "849106",
    "Rentenfonds",
    2,
    "<5",
    "Weltweit",
    false,
    "Core",
    "target-2031",
  ),
  p(
    "highyield",
    "UniEuroRenta HighYield",
    "975783",
    "Rentenfonds",
    3,
    ">5",
    "Weltweit",
    false,
    "Core",
    "mixed",
  ),
  p(
    "reserve-plus",
    "UniInstitutional Euro Reserve Plus",
    "A1C81J",
    "Rentenfonds",
    1,
    "<3",
    "Weltweit",
    false,
    "Core",
    "money-market",
  ),
  p(
    "premium-corporate",
    "UniInstitutional Premium Corporate Bonds",
    "A1C81E",
    "Rentenfonds",
    2,
    "<5",
    "Weltweit",
    false,
    "Core",
    "target-2031",
  ),

  p(
    "uniimmo-de",
    "UniImmo: Deutschland",
    "980550",
    "Immobilienfonds",
    1,
    "<5",
    "Deutschland",
    true,
    "Core",
    "defensive-mixed",
  ),
  p(
    "uniimmo-eu",
    "UniImmo: Europa",
    "980551",
    "Immobilienfonds",
    1,
    "<5",
    "Europa",
    true,
    "Core",
    "defensive-mixed",
  ),
  p(
    "hausinvest",
    "hausInvest",
    "980701",
    "Immobilienfonds",
    2,
    "<5",
    "Europa",
    true,
    "Core",
    "defensive-mixed",
  ),
  p(
    "private-finance",
    "Allianz PrivateFinancePolice",
    "-",
    "Alternative Anlagen",
    3,
    ">5",
    "Weltweit",
    true,
    "Satellit",
    "mixed",
  ),
  p(
    "uniopti4",
    "UniOpti4",
    "A0KEBS",
    "Geldmarkt",
    1,
    "<3",
    "Weltweit",
    false,
    "Core",
    "money-market",
  ),
  p(
    "union-geldmarkt",
    "UnionGeldmarktFonds",
    "975013",
    "Geldmarkt",
    1,
    "<3",
    "Weltweit",
    false,
    "Core",
    "money-market",
  ),
  p(
    "xetra-gold",
    "Xetra-Gold",
    "A0S9GB",
    "Alternative Anlagen",
    3,
    "<5",
    "Weltweit",
    false,
    "Satellit",
    "mixed",
  ),
  p(
    "zinsfix",
    "ZinsFix Index",
    "-",
    "Zertifikat",
    2,
    ">1,5",
    "Europa",
    false,
    "Satellit",
    "certificates",
  ),
  p(
    "mea",
    "MEA Einzelwert",
    "-",
    "Zertifikat",
    3,
    ">1,5",
    "Europa",
    false,
    "Satellit",
    "certificates",
  ),
];

export type ModelPortfolio = {
  id: "rb2" | "rb3" | "rb4";
  name: string;
  risk: RiskLevel;
  mix: Record<string, number>;
  holdings: Array<{ productId: string; name: string; weight: number }>;
};

export const modelPortfolios: ModelPortfolio[] = [
  {
    id: "rb2",
    name: "Modellportfolio RB 2",
    risk: 2,
    mix: {
      Liquidität: 0,
      Geldwerte: 70,
      Substanzwerte: 20,
      "Alternative Anlagen": 10,
      Sachwerte: 0,
    },
    holdings: [
      { productId: "ps-defensiv", name: "Private Select Defensiv", weight: 50 },
      {
        productId: "uer-2032",
        name: "UER Unternehmensanleihen 2032 -net- A",
        weight: 15,
      },
      {
        productId: "carmignac-2029",
        name: "Carmignac Credit 2029",
        weight: 10,
      },
      { productId: "uer-corporates", name: "UER Corporates A", weight: 7.5 },
      {
        productId: "dividendenass",
        name: "UniDividendenAss -net- A",
        weight: 2.5,
      },
      { productId: "marktführer", name: "UniMarktführer -net- A", weight: 2.5 },
      { productId: "zinsfix", name: "ZinsFix Index", weight: 2.5 },
      { productId: "xetra-gold", name: "Xetra-Gold", weight: 5 },
      {
        productId: "private-finance",
        name: "Allianz PrivateFinancePolice",
        weight: 5,
      },
    ],
  },
  {
    id: "rb3",
    name: "Modellportfolio RB 3",
    risk: 3,
    mix: {
      Liquidität: 0,
      Geldwerte: 45,
      Substanzwerte: 40,
      "Alternative Anlagen": 15,
      Sachwerte: 0,
    },
    holdings: [
      {
        productId: "ps-ausgewogen",
        name: "Private Select Ausgewogen",
        weight: 50,
      },
      {
        productId: "uer-2032",
        name: "UER Unternehmensanleihen 2032 -net- A",
        weight: 7.5,
      },
      { productId: "carmignac-2029", name: "Carmignac Credit 2029", weight: 5 },
      { productId: "uer-corporates", name: "UER Corporates A", weight: 5 },
      {
        productId: "dividendenass",
        name: "UniDividendenAss -net- A",
        weight: 5,
      },
      { productId: "marktführer", name: "UniMarktführer -net- A", weight: 5 },
      { productId: "zinsfix", name: "ZinsFix Index", weight: 5 },
      { productId: "mea", name: "MEA Einzelwert", weight: 2.5 },
      { productId: "xetra-gold", name: "Xetra-Gold", weight: 7.5 },
      {
        productId: "private-finance",
        name: "Allianz PrivateFinancePolice",
        weight: 7.5,
      },
    ],
  },
  {
    id: "rb4",
    name: "Modellportfolio RB 4",
    risk: 4,
    mix: {
      Liquidität: 0,
      Geldwerte: 20,
      Substanzwerte: 60,
      "Alternative Anlagen": 20,
      Sachwerte: 0,
    },
    holdings: [
      { productId: "ps-offensiv", name: "Private Select Offensiv", weight: 50 },
      {
        productId: "carmignac-2031",
        name: "Carmignac Credit 2031",
        weight: 2.5,
      },
      {
        productId: "dividendenass",
        name: "UniDividendenAss -net- A",
        weight: 10,
      },
      { productId: "marktführer", name: "UniMarktführer -net- A", weight: 7.5 },
      { productId: "zinsfix", name: "ZinsFix Index", weight: 5 },
      { productId: "mea", name: "MEA Einzelwert", weight: 5 },
      { productId: "xetra-gold", name: "Xetra-Gold", weight: 10 },
      {
        productId: "private-finance",
        name: "Allianz PrivateFinancePolice",
        weight: 10,
      },
    ],
  },
];

export type ManagedPortfolio = {
  id: string;
  name: string;
  sustainable: boolean;
  currency: "EUR" | "CHF";
  region: string;
  metals: "Ja" | "Nein" | "Individuell";
  targetFunds: boolean;
  individual: boolean;
  risk: number;
  minimum: number;
  custody: string;
  horizon: string;
  mix: string;
  costs: string;
  billingCountry: "Deutschland" | "Schweiz";
  equityBand: "Unter 50%" | "Über 50%" | "Individuell";
  assetMix: AssetMix | null;
  onHouseView: boolean;
  sourceLabel?: string;
};

const vv = (
  id: string,
  name: string,
  sustainable: boolean,
  currency: "EUR" | "CHF",
  region: string,
  metals: "Ja" | "Nein" | "Individuell",
  targetFunds: boolean,
  individual: boolean,
  risk: number,
  minimum: number,
  custody: string,
  mixText: string,
  costs: string,
  assetMix: AssetMix,
  onHouseView = true,
): ManagedPortfolio => ({
  id,
  name,
  sustainable,
  currency,
  region,
  metals,
  targetFunds,
  individual,
  risk,
  minimum,
  custody,
  horizon: "> 5 Jahre",
  mix: mixText,
  costs,
  billingCountry: currency === "CHF" ? "Schweiz" : "Deutschland",
  equityBand: individual
    ? "Individuell"
    : assetMix.Substanzwerte > 50
      ? "Über 50%"
      : "Unter 50%",
  assetMix,
  onHouseView,
});

export const managedPortfolios: ManagedPortfolio[] = [
  {
    ...vv(
      "ps-sicherheit",
      "Private Select Sicherheit",
      false,
      "EUR",
      "Weltweit",
      "Nein",
      true,
      false,
      2,
      125000,
      "VoBa pur",
      "80 % Geldwerte / 20 % Substanzwerte",
      "1,38–1,58 %",
      mix(0, 80, 20),
    ),
    sourceLabel: "Bezeichnung aus VV-Selektionsmatrix",
  },
  {
    ...vv(
      "ps-ertrag",
      "Private Select Ertrag",
      false,
      "EUR",
      "Weltweit",
      "Nein",
      true,
      false,
      3,
      125000,
      "VoBa pur",
      "60 % Geldwerte / 40 % Substanzwerte",
      "1,38–1,58 %",
      mix(0, 60, 40),
    ),
    sourceLabel: "Bezeichnung aus VV-Selektionsmatrix",
  },
  {
    ...vv(
      "ps-wachstum",
      "Private Select Wachstum",
      false,
      "EUR",
      "Weltweit",
      "Nein",
      true,
      false,
      3,
      125000,
      "VoBa pur",
      "40 % Geldwerte / 60 % Substanzwerte",
      "1,38–1,58 %",
      mix(0, 40, 60),
    ),
    sourceLabel: "Bezeichnung aus VV-Selektionsmatrix",
  },
  {
    ...vv(
      "ps-chance",
      "Private Select Chance",
      false,
      "EUR",
      "Weltweit",
      "Nein",
      true,
      false,
      4,
      125000,
      "VoBa pur",
      "100 % Substanzwerte",
      "1,38–1,58 %",
      mix(0, 0, 100),
    ),
    sourceLabel: "Bezeichnung aus VV-Selektionsmatrix",
  },
  {
    ...vv(
      "ps-defensiv",
      "Private Select Defensiv",
      false,
      "EUR",
      "Weltweit",
      "Nein",
      true,
      false,
      2,
      125000,
      "VoBa pur",
      "Strategiebezeichnung aus der Modellportfolio-Unterlage",
      "noch abzustimmen",
      mix(),
      false,
    ),
    assetMix: null,
    sourceLabel: "Bezeichnung aus Modellportfolio-Unterlage",
  },
  {
    ...vv(
      "ps-ausgewogen",
      "Private Select Ausgewogen",
      false,
      "EUR",
      "Weltweit",
      "Nein",
      true,
      false,
      3,
      125000,
      "VoBa pur",
      "Strategiebezeichnung aus der Modellportfolio-Unterlage",
      "noch abzustimmen",
      mix(),
      false,
    ),
    assetMix: null,
    sourceLabel: "Bezeichnung aus Modellportfolio-Unterlage",
  },
  {
    ...vv(
      "ps-offensiv",
      "Private Select Offensiv",
      false,
      "EUR",
      "Weltweit",
      "Nein",
      true,
      false,
      4,
      125000,
      "VoBa pur",
      "Strategiebezeichnung aus der Modellportfolio-Unterlage",
      "noch abzustimmen",
      mix(),
      false,
    ),
    assetMix: null,
    sourceLabel: "Bezeichnung aus Modellportfolio-Unterlage",
  },
  vv(
    "mondial-ausgewogen",
    "VV mondial ausgewogen",
    false,
    "EUR",
    "Weltweit",
    "Ja",
    false,
    false,
    3,
    500000,
    "VoBa pur",
    "45 % Geldwerte / 45 % Substanzwerte / 10 % andere Anlagen",
    "1,7 % p. a., mind. 3.000 €",
    mix(0, 45, 45, 10),
  ),
  vv(
    "mondial-wachstum",
    "VV mondial Wachstum",
    false,
    "EUR",
    "Weltweit",
    "Ja",
    false,
    false,
    3,
    250000,
    "VoBa pur",
    "20 % Geldwerte / 70 % Substanzwerte / 10 % andere Anlagen",
    "1,8 % p. a., mind. 3.000 €",
    mix(0, 20, 70, 10),
  ),
  vv(
    "mondial-fonds",
    "VV mondial ausgewogen Fondslösung",
    false,
    "EUR",
    "Weltweit",
    "Ja",
    false,
    false,
    3,
    60000,
    "VoBa pur",
    "45 % Geldwerte / 45 % Substanzwerte / 10 % andere Anlagen",
    "1,7 %",
    mix(0, 45, 45, 10),
  ),
  vv(
    "swiss-gold",
    "Swiss Gold Plus in CHF",
    false,
    "CHF",
    "Schweiz",
    "Ja",
    true,
    false,
    3,
    100000,
    "DZ Privatbank",
    "je 33 % Geldwerte, Substanzwerte und andere Anlagen",
    "1,5 % p. a., mind. 700 €",
    mix(0, 33, 33, 34),
  ),
  vv(
    "swiss-gold-active",
    "Swiss Gold Plus Active CHF",
    false,
    "CHF",
    "Schweiz",
    "Ja",
    true,
    false,
    3,
    100000,
    "DZ Privatbank",
    "je 33 % Geldwerte, Substanzwerte und andere Anlagen",
    "1,5 % p. a., mind. 750 €",
    mix(0, 33, 33, 34),
  ),
  vv(
    "swiss-innovation",
    "Swiss Innovation Plus",
    false,
    "CHF",
    "Schweiz",
    "Nein",
    true,
    false,
    3,
    100000,
    "DZ Privatbank",
    "35 % Geldwerte / 65 % Substanzwerte",
    "0,95–1,70 %",
    mix(0, 35, 65),
  ),
  vv(
    "ethisch-fonds",
    "Ethisch-Nachhaltig ausgewogen Fondslösung",
    true,
    "EUR",
    "Weltweit",
    "Nein",
    false,
    false,
    3,
    60000,
    "DZ Privatbank",
    "50 % Geldwerte / 50 % Substanzwerte",
    "1,7 % p. a.",
    mix(0, 50, 50),
  ),
  vv(
    "ethisch-depot",
    "Ethisch-Nachhaltig ausgewogen Depotlösung",
    true,
    "EUR",
    "Weltweit",
    "Nein",
    false,
    false,
    3,
    500000,
    "VoBa pur",
    "50 % Geldwerte / 50 % Substanzwerte",
    "1,7 % p. a., mind. 3.000 €",
    mix(0, 50, 50),
  ),
  ...[20, 40, 60, 80, 100].map((equity) =>
    vv(
      `wertanlage-${equity}`,
      `WertAnlage ${equity} klassisch`,
      false,
      "EUR",
      "Weltweit",
      "Individuell",
      true,
      true,
      equity <= 40 ? 2 : 3,
      50000,
      "Union Investment",
      `${equity} % strategischer Substanzanteil, individualisierbar`,
      "ca. 2,82 %",
      mix(0, 100 - equity, equity),
    ),
  ),
  ...[20, 40, 60, 80, 100].map((equity) =>
    vv(
      `wertanlage-${equity}-nachhaltig`,
      `WertAnlage ${equity} nachhaltig`,
      true,
      "EUR",
      "Weltweit",
      "Nein",
      true,
      true,
      equity <= 40 ? 2 : 3,
      50000,
      "Union Investment",
      `${equity} % strategischer Substanzanteil, individualisierbar`,
      "ca. 2,82 %",
      mix(0, 100 - equity, equity),
    ),
  ),
  ...[1, 2, 3, 4].map((strategy, index) => {
    const equity = [25, 45, 65, 85][index];
    return vv(
      `vermoegenplus-${strategy}`,
      `VermögenPlus Strategie ${["I", "II", "III", "IV"][index]}`,
      false,
      "EUR",
      "Weltweit",
      "Individuell",
      true,
      false,
      strategy === 1 ? 2 : 3,
      500,
      "Union Investment",
      `Multi-Asset-Strategie ${strategy}`,
      "1,39 %",
      mix(0, 100 - equity, equity),
      false,
    );
  }),
  ...[1, 2, 3, 4].map((strategy, index) => {
    const equity = [25, 45, 65, 85][index];
    return vv(
      `vermoegenplus-n-${strategy}`,
      `VermögenPlus Nachhaltig Strategie ${strategy}`,
      true,
      "EUR",
      "Weltweit",
      "Nein",
      true,
      false,
      strategy === 1 ? 2 : 3,
      500,
      "Union Investment",
      `Nachhaltige Multi-Asset-Strategie ${strategy}`,
      "1,39 %",
      mix(0, 100 - equity, equity),
      false,
    );
  }),
];

export const dataSources = [
  { title: "Laufzeiten & Renditebandbreiten", date: "07.05.2026" },
  { title: "Modellportfolios PB", date: "01.07.2026" },
  { title: "Hausmeinung Fonds-Matrix", date: "01.07.2026" },
  { title: "VV-Selektionsmatrix", date: "20.02.2026" },
  { title: "Depotoptimierer KCI", date: "15.07.2026" },
];
