import assert from "node:assert/strict";
import {
  type AdvisoryCase, type CaseSnapshot, type StructurePlan,
  blankVvFilters, duplicateStructurePlan, nextPlanCopyName, normalizeImportedCase,
} from "../app/case-model";
import { CASE_STORAGE_KEY, readCaseStore, writeCaseStore } from "../app/case-storage";
import { emptyAdvisory } from "../app/navigator-config";

// All entities and relations are explicit synthetic inputs, not generated by
// production create/copy helpers. No real customer, person or bank data.
const AS_OF = "2026-01-01T12:00:00.000Z";
function fixture(): AdvisoryCase {
  const planA: StructurePlan = {
    id: "p4-plan-a", name: "Synthetischer Plan A", total: 50_000,
    capitalMode: "manual", preferred: true, notes: "Synthetische Planung",
    modelId: "synthetic-model", modelAmount: 30_000,
    depotMode: "retain", depotHoldingIds: ["p4-holding-a", "p4-holding-b"],
    depotSelectionInitialized: true, depotModeSelectionInitialized: true,
    createdAt: AS_OF, updatedAt: AS_OF,
    allocations: [
      {
        id: "p4-allocation-a1", productId: "synthetic-product-one",
        productName: "Synthetisches Produkt eins", solutionId: "synthetic-solution-one",
        source: "model", modelId: "synthetic-model", amount: 10_000,
        allocationMode: "single", bucketId: "year5", bucketAmounts: { year5: 10_000 },
        capitalPotId: "year-2030", capitalPotAmounts: { "year-2030": 10_000 },
      },
      {
        id: "p4-allocation-a2", productId: "synthetic-product-two",
        productName: "Synthetisches Produkt zwei", solutionId: "synthetic-solution-two",
        source: "product", amount: 30_000, allocationMode: "manual",
        bucketId: "year10plus", bucketAmounts: { year10plus: 30_000 },
        capitalPotId: "strategic", capitalPotAmounts: { strategic: 30_000 },
      },
    ],
    investmentPlans: [
      {
        id: "p4-phase-a1", type: "phased", allocationId: "p4-allocation-a1",
        capitalPotId: "year-2030", stagedMode: "percent", stagedValue: 50,
        installments: 5, frequency: "monthly", startDate: "2026-10-01", note: "Einstieg eins",
      },
      {
        id: "p4-phase-a2", type: "phased", allocationId: "p4-allocation-a2",
        capitalPotId: "strategic", stagedMode: "amount", stagedValue: 12_000,
        installments: 4, frequency: "quarterly", startDate: "2026-10-15", note: "Einstieg zwei",
      },
      {
        id: "p4-savings-goal", type: "savings", name: "Synthetischer Zielsparplan",
        productId: "synthetic-product-one", productName: "Synthetisches Produkt eins",
        contributionAmount: 100, frequency: "monthly", startDate: "2026-10-01",
        targetRef: { kind: "savingsGoal", id: "p4-goal" }, note: "Caseweites Ziel",
      },
      {
        id: "p4-savings-need", type: "savings", name: "Synthetischer Bedarfssparplan",
        productId: "synthetic-product-two", productName: "Synthetisches Produkt zwei",
        contributionAmount: 200, frequency: "annual", startDate: "2026-11-01",
        targetRef: { kind: "need", id: 41 }, note: "Caseweiter Bedarf",
      },
    ],
  };
  const item: AdvisoryCase = {
    schemaVersion: 11, id: "p4-original-case", status: "Entwurf", advisorId: "leon-moebius",
    advisory: {
      ...structuredClone(emptyAdvisory), caseName: "Synthetischer P4-Fall", scope: "private",
      liquidAssets: 50_000, reserve: 0, hasDepot: true, depotValue: 3_000,
      needs: [{ id: 41, purpose: "Synthetischer Bedarf", amount: 10_000, years: 4, dueDate: "2030-01-01" }],
      modules: ["maturity"],
    },
    plans: [planA, {
      id: "p4-plan-b", name: "Synthetischer Plan B", total: 50_000, capitalMode: "manual",
      allocations: [], investmentPlans: [], preferred: false, notes: "Aktiver Entwurf",
      depotMode: "compare", depotHoldingIds: ["p4-holding-b"],
      depotSelectionInitialized: true, depotModeSelectionInitialized: true,
      createdAt: AS_OF, updatedAt: AS_OF,
    }],
    activePlanId: "p4-plan-b",
    depotAccounts: [
      { id: "p4-depot-a", name: "Synthetisches Depot A", createdAt: AS_OF, updatedAt: AS_OF },
      { id: "p4-depot-b", name: "Synthetisches Depot B", createdAt: AS_OF, updatedAt: AS_OF },
    ],
    depot: [
      { id: "p4-holding-a", depotId: "p4-depot-a", productId: "synthetic-product-one",
        name: "Synthetische Position A", value: 1_000, assetClass: "Geldwerte", region: "Weltweit",
        risk: 2, plannedSale: 100, note: "Position A", classificationStatus: "mapped" },
      { id: "p4-holding-b", depotId: "p4-depot-b", productId: "synthetic-product-two",
        name: "Synthetische Position B", value: 2_000, assetClass: "Substanzwerte", region: "Weltweit",
        risk: 3, plannedSale: 0, note: "Position B", classificationStatus: "mapped" },
    ],
    savingsGoals: [{ id: "p4-goal", name: "Synthetisches Sparziel", targetAmount: 5_000,
      targetYear: 2030, targetDate: "2030-01-01", note: "Caseweites Ziel" }],
    customerChecklist: [{ id: "p4-checklist", text: "Synthetischer nächster Schritt",
      category: "Sonstiger nächster Schritt", done: false, source: "module",
      moduleId: "maturity", slideIndex: 1, createdAt: AS_OF }],
    moduleStates: { maturity: { status: "in_progress", currentSlide: 1,
      checklist: { "synthetic-check": true }, notes: "Synthetisches Modul", updatedAt: AS_OF } },
    vvFilters: blankVvFilters(50_000), selectedVvIds: ["synthetic-vv"], currentStep: 2,
    createdAt: AS_OF, updatedAt: AS_OF, versions: [],
  };
  // Construct snapshots independently of caseSnapshot and keep historical IDs
  // deliberately distinct from the future current import identity.
  const { versions: unused, ...snapshot } = structuredClone(item);
  const older: CaseSnapshot = { ...structuredClone(snapshot), id: "p4-historical-case", status: "In Prüfung" };
  older.plans[0].notes = "Synthetischer historischer Inhalt";
  item.versions = [
    { id: "p4-version-old", label: "Synthetische alte Version", createdAt: AS_OF, snapshot: older },
    { id: "p4-version-new", label: "Synthetische neue Version", createdAt: AS_OF, snapshot },
  ];
  return item;
}

function identitiesAndReferences(item: AdvisoryCase) {
  return {
    depots: item.depotAccounts.map((d) => d.id),
    holdings: item.depot.map((h) => [h.id, h.depotId]),
    plans: item.plans.map((p) => ({ id: p.id, preferred: p.preferred, holdings: p.depotHoldingIds,
      allocations: p.allocations.map((a) => a.id),
      investments: p.investmentPlans.map((i) => i.type === "phased"
        ? [i.id, i.type, i.allocationId, i.capitalPotId]
        : [i.id, i.type, i.targetRef]),
    })),
    active: item.activePlanId, needs: item.advisory.needs.map((n) => n.id),
    goals: item.savingsGoals.map((g) => g.id), checklist: item.customerChecklist.map((c) => c.id),
    versions: item.versions.map((v) => [v.id, v.snapshot.id]),
    advisor: item.advisorId, modules: item.advisory.modules,
    moduleStates: Object.keys(item.moduleStates), checklistModule: item.customerChecklist[0].moduleId,
    vv: item.selectedVvIds,
    catalog: {
      holdings: item.depot.map((h) => h.productId),
      plans: item.plans.map((p) => [p.modelId ?? null,
        p.allocations.map((a) => [a.productId, a.solutionId, a.modelId ?? null, a.capitalPotId,
          a.capitalPotAmounts, a.bucketId, a.bucketAmounts]),
        p.investmentPlans.filter((i) => i.type === "savings").map((i) => i.productId)]),
    },
  };
}

const expectedGraph = {
  depots: ["p4-depot-a", "p4-depot-b"],
  holdings: [["p4-holding-a", "p4-depot-a"], ["p4-holding-b", "p4-depot-b"]],
  plans: [
    { id: "p4-plan-a", preferred: true, holdings: ["p4-holding-a", "p4-holding-b"],
      allocations: ["p4-allocation-a1", "p4-allocation-a2"], investments: [
        ["p4-phase-a1", "phased", "p4-allocation-a1", "year-2030"],
        ["p4-phase-a2", "phased", "p4-allocation-a2", "strategic"],
        ["p4-savings-goal", "savings", { kind: "savingsGoal", id: "p4-goal" }],
        ["p4-savings-need", "savings", { kind: "need", id: 41 }],
      ] },
    { id: "p4-plan-b", preferred: false, holdings: ["p4-holding-b"], allocations: [], investments: [] },
  ],
  active: "p4-plan-b", needs: [41], goals: ["p4-goal"], checklist: ["p4-checklist"],
  versions: [["p4-version-old", "p4-historical-case"], ["p4-version-new", "p4-original-case"]],
  advisor: "leon-moebius", modules: ["maturity"], moduleStates: ["maturity"],
  checklistModule: "maturity", vv: ["synthetic-vv"],
  catalog: {
    holdings: ["synthetic-product-one", "synthetic-product-two"],
    plans: [["synthetic-model", [
      ["synthetic-product-one", "synthetic-solution-one", "synthetic-model", "year-2030",
        { "year-2030": 10_000 }, "year5", { year5: 10_000 }],
      ["synthetic-product-two", "synthetic-solution-two", null, "strategic",
        { strategic: 30_000 }, "year10plus", { year10plus: 30_000 }],
    ], ["synthetic-product-one", "synthetic-product-two"]], [null, [], []]],
  },
};

function validRelations(item: AdvisoryCase) {
  assert.ok(item.plans.some((p) => p.id === item.activePlanId), "Active plan belongs to this case");
  for (const holding of item.depot)
    assert.ok(item.depotAccounts.some((d) => d.id === holding.depotId));
  for (const plan of item.plans) {
    for (const id of plan.depotHoldingIds) assert.ok(item.depot.some((h) => h.id === id));
    for (const entry of plan.investmentPlans) {
      if (entry.type === "phased") {
        const allocation = plan.allocations.find((a) => a.id === entry.allocationId);
        assert.ok(allocation, "Phased entry belongs to its own plan");
        assert.ok((allocation.capitalPotAmounts?.[entry.capitalPotId] ?? 0) > 0);
      } else if (entry.targetRef?.kind === "savingsGoal") {
        const id = entry.targetRef.id;
        assert.ok(item.savingsGoals.some((g) => g.id === id));
      } else if (entry.targetRef?.kind === "need") {
        const id = entry.targetRef.id;
        assert.ok(item.advisory.needs.some((n) => n.id === id));
      }
    }
  }
}

// Check every mutable object/array, including nested historical snapshots.
function objectGraph(value: unknown, result = new Set<object>()): Set<object> {
  if (value && typeof value === "object" && !result.has(value)) {
    result.add(value);
    Object.values(value).forEach((child) => objectGraph(child, result));
  }
  return result;
}
function noAliases(source: unknown, copy: unknown) {
  const objects = objectGraph(source);
  for (const object of objectGraph(copy)) assert.ok(!objects.has(object), "Copy shares no mutable object with source");
}
function freshTimestamp(value: string, started: number, finished: number) {
  const time = Date.parse(value);
  assert.ok(Number.isFinite(time) && time >= started && time <= finished, "Timestamp belongs to operation window");
}
class MemoryStorage {
  values = new Map<string, string>();
  get length() { return this.values.size; }
  key(index: number) { return [...this.values.keys()][index] ?? null; }
  getItem(key: string) { return this.values.get(key) ?? null; }
  setItem(key: string, value: string) { this.values.set(key, value); }
}
let groups = 0;
function test(name: string, run: () => void) {
  run(); groups++;
  console.log(`PASS P4 ${name}`);
}

test("case import: new outer ID, stable explicit inner graph and historical snapshots", () => {
  // Both the direct helper input and the actual full-backup envelope are supported.
  for (const envelope of [false, true]) {
    const source = fixture();
    assert.equal(source.id, "p4-original-case");
    assert.deepEqual(identitiesAndReferences(source), expectedGraph);
    const input = envelope ? { exportedAt: AS_OF, case: source } : source;
    const before = JSON.stringify(input);
    const started = Date.now();
    const imported = normalizeImportedCase(input);
    const finished = Date.now();
    assert.ok(imported);
    assert.equal(imported.schemaVersion, 11);
    assert.ok(imported.id && imported.id !== "p4-original-case");
    assert.deepEqual(identitiesAndReferences(imported), expectedGraph, "No deep rekeying on a case import");
    assert.deepEqual(imported.versions, source.versions, "Entire history is copied without normalization/rekeying");
    assert.ok(imported.versions.every((v) => v.snapshot.id !== imported.id));
    assert.equal(imported.createdAt, AS_OF);
    freshTimestamp(imported.updatedAt, started, finished);
    assert.equal(imported.advisory.depotValue, 3_000);
    validRelations(imported);
    noAliases(source, imported);
    assert.equal(JSON.stringify(input), before, "Import must not mutate its input");

    // Store both namespaces together: equal inner IDs are intentional and loadable.
    const storage = new MemoryStorage();
    writeCaseStore(storage, [source, imported]);
    const read = readCaseStore(storage.getItem(CASE_STORAGE_KEY));
    assert.equal(read.recoveryNeeded, false);
    assert.equal(read.protectedEntries.length, 0);
    assert.deepEqual(read.cases.map((c) => c.id).sort(), [source.id, imported.id].sort());
    for (const item of read.cases) assert.deepEqual(identitiesAndReferences(item), expectedGraph);

    imported.advisory.needs[0].purpose = "Bearbeitete Kopie";
    imported.plans[0].allocations[0].capitalPotAmounts!["year-2030"] = 999;
    imported.plans[0].depotHoldingIds.push("synthetic-copy-only");
    const savings = imported.plans[0].investmentPlans[2];
    assert.equal(savings.type, "savings");
    savings.targetRef!.id = "synthetic-copy-goal";
    imported.depot[0].note = "Bearbeitete Position";
    imported.depotAccounts[0].name = "Bearbeitetes Depot";
    imported.savingsGoals[0].name = "Bearbeitetes Sparziel";
    imported.customerChecklist[0].done = true;
    imported.moduleStates.maturity.checklist["synthetic-check"] = false;
    imported.vvFilters.amount = 1;
    imported.selectedVvIds.push("synthetic-copy-vv");
    imported.versions[0].snapshot.plans[0].notes = "Bearbeiteter historischer Inhalt";
    imported.versions.push(structuredClone(imported.versions[1]));
    assert.equal(JSON.stringify(input), before, "Editing imported live state/history must not change source");
    // P3 rejects the deliberately dangling alias probes above. Repair only this
    // synthetic test copy before the independent-namespace persistence assertion.
    const storeBefore = [...storage.values];
    assert.throws(() => writeCaseStore(storage, [source, imported]));
    assert.deepEqual([...storage.values], storeBefore);
    imported.plans[0].depotHoldingIds.pop();
    savings.targetRef!.id = "p4-goal";
    imported.versions[imported.versions.length - 1].id = "p4-copy-version";
    writeCaseStore(storage, [source, imported]);
    const persisted = JSON.parse(storage.getItem(CASE_STORAGE_KEY)!) as AdvisoryCase[];
    assert.deepEqual(persisted.find((c) => c.id === source.id), source, "Editing/saving the copy preserves the original namespace");
    assert.equal(persisted.length, 2);
  }
});

test("active versus preferred: independent selections and a valid draft without preference", () => {
  for (const preferred of [true, false]) {
    const source = fixture();
    source.plans[0].preferred = preferred;
    const before = JSON.stringify(source);
    const imported = normalizeImportedCase(source);
    assert.ok(imported);
    assert.equal(imported.status, "Entwurf");
    assert.equal(imported.activePlanId, "p4-plan-b");
    assert.deepEqual(imported.plans.map((p) => [p.id, p.preferred]), [
      ["p4-plan-a", preferred], ["p4-plan-b", false],
    ]);
    assert.equal(imported.plans.filter((p) => p.preferred).length, preferred ? 1 : 0);
    validRelations(imported);
    assert.equal(JSON.stringify(source), before);
  }
});

test("load: retain current case ID and inner identities without creating a case", () => {
  const source = fixture(), before = JSON.stringify(source);
  const loaded = normalizeImportedCase(source, false);
  assert.ok(loaded);
  assert.equal(loaded.id, "p4-original-case");
  assert.deepEqual(identitiesAndReferences(loaded), expectedGraph);
  assert.deepEqual(loaded.versions, source.versions);
  assert.equal(JSON.stringify(source), before);
});

test("plan copies: fresh identities across variants, relational remapping, stable case/catalog references", () => {
  const sourceCase = fixture(), source = sourceCase.plans[0];
  const before = JSON.stringify(sourceCase);
  const copies: StructurePlan[] = [];
  for (let index = 0; index < 3; index++) {
    const name = nextPlanCopyName(source.name, [...sourceCase.plans, ...copies].map((p) => p.name));
    assert.equal(name, `${source.name} – Kopie${index === 0 ? "" : ` ${index + 1}`}`);
    const started = Date.now(), copy = duplicateStructurePlan(source, name), finished = Date.now();
    assert.equal(copy.name, name);
    assert.notEqual(copy.id, "p4-plan-a");
    assert.equal(copy.preferred, false);
    assert.equal(source.preferred, true);
    assert.equal(sourceCase.activePlanId, "p4-plan-b", "Helper must not change case-level selection");
    freshTimestamp(copy.createdAt, started, finished);
    freshTimestamp(copy.updatedAt, started, finished);
    assert.equal(copy.allocations.length, 2);
    assert.equal(copy.investmentPlans.length, 4);
    const mapping = new Map(source.allocations.map((a, i) => [a.id, copy.allocations[i].id]));
    copy.allocations.forEach((allocation, i) => {
      assert.notEqual(allocation.id, source.allocations[i].id);
      assert.deepEqual({ ...allocation, id: source.allocations[i].id }, source.allocations[i],
        "Only allocation identity changes: product/model/solution/pot references stay stable");
    });
    copy.investmentPlans.forEach((entry, i) => {
      const original = source.investmentPlans[i];
      assert.notEqual(entry.id, original.id);
      assert.equal(entry.type, original.type);
      if (entry.type === "phased" && original.type === "phased") {
        assert.equal(entry.allocationId, mapping.get(original.allocationId), "Remap to the corresponding allocation, not just any new ID");
        assert.ok(!source.allocations.some((a) => a.id === entry.allocationId));
        assert.deepEqual({ ...entry, id: original.id, allocationId: original.allocationId }, original);
      } else {
        assert.deepEqual({ ...entry, id: original.id }, original, "Savings target and product references stay case/catalog-wide");
      }
    });
    assert.deepEqual({ ...copy, id: source.id, name: source.name, preferred: source.preferred,
      allocations: source.allocations, investmentPlans: source.investmentPlans,
      createdAt: source.createdAt, updatedAt: source.updatedAt }, source, "Other plan content and depot references stay stable");
    noAliases(source, copy);
    for (const sibling of copies) noAliases(sibling, copy);
    copies.push(copy);
    assert.equal(JSON.stringify(sourceCase), before, "Copy leaves source plan, IDs, references and preferences unchanged");
  }
  const plans = [...sourceCase.plans, ...copies];
  for (const ids of [plans.map((p) => p.id), plans.flatMap((p) => p.allocations.map((a) => a.id)),
    plans.flatMap((p) => p.investmentPlans.map((i) => i.id))]) {
    assert.ok(ids.every(Boolean));
    assert.equal(new Set(ids).size, ids.length, "No plan-internal identity collisions across variants");
  }
  validRelations({ ...sourceCase, plans });
  const siblingBefore = copies.slice(1).map((p) => JSON.stringify(p));
  const copy = copies[0];
  copy.allocations[0].amount += 1;
  copy.allocations[0].capitalPotAmounts!["year-2030"] = 1;
  copy.allocations[0].bucketAmounts!.year5 = 1;
  copy.allocations.push(structuredClone(copy.allocations[1]));
  copy.depotHoldingIds.push("synthetic-copy-only");
  const savings = copy.investmentPlans[2];
  assert.equal(savings.type, "savings");
  savings.targetRef!.id = "synthetic-copy-goal";
  copy.investmentPlans[0].note = "Bearbeiteter Einstieg";
  copy.investmentPlans.push(structuredClone(copy.investmentPlans[3]));
  copy.notes = "Bearbeitete Planung";
  copy.preferred = true;
  assert.equal(JSON.stringify(sourceCase), before, "Mutating nested copied plan data must not change its source");
  assert.deepEqual(copies.slice(1).map((p) => JSON.stringify(p)), siblingBefore, "Copies are independent of each other");
});

console.log(`P4 copy/import contract: ${groups} groups passed; explicit synthetic identities, no timing/random-ID assumptions. Restore handler remains covered by CP0A2/CP0B.`);
