import assert from "node:assert/strict";
import { annualAccruedCheck, annualBondCalendar, bondPresentValue, datedBondDuration, solveBondYield } from "../app/bond-math";
import { analyzeBondV2, BondPriceInput, calculateBondModel, resolveBondPrice } from "../app/bond-v2";
import { structureOverviewSource, validBondSource } from "../app/bond-source";
import { parseDepotCsv } from "../app/depot-csv";
import { addDepotAccount, createCase, caseSnapshot, normalizeImportedCase, replaceDepotAccount } from "../app/case-model";
import { bondPortfolioAnalysis, buildDepotAnalysisPositions, classifyDepotProduct, DepotAnalysisPosition } from "../app/depot-analysis";
import { CASE_STORAGE_KEY, readCaseStore, recoveryBackups, writeCaseStore } from "../app/case-storage";

let count = 0;
function test(name: string, run: () => void) { run(); count++; console.log(`PASS ${name}`); }
function close(actual: number | null | undefined, expected: number, tolerance = 1e-9) {
  assert.ok(actual !== null && actual !== undefined && Number.isFinite(actual) && Math.abs(actual - expected) <= tolerance, `${actual} != ${expected} (tol ${tolerance})`);
}
const csv = (text: string) => parseDepotCsv(new TextEncoder().encode(text).buffer);
const header = "Bezeichnung;Wertpapiertyp;Anlagemedium;Anlagesegment;Währung;Zinssatz;Endfälligkeit;Stück/Nominal;Kurs;Kurswert incl. Stückzinsen;Stückzinsen;Devisenkurs;Bewertungsende";
function imported(extra: Partial<DepotAnalysisPosition> = {}): DepotAnalysisPosition {
  const raw = csv(`${header}\nSynthetisch;Festverzinsliche;;;EUR;5;01.01.2027;10000;100;10000;0;1;01.01.2026`).rows[0];
  const holding = { ...raw, ...extra };
  return { ...holding, bondSource: structureOverviewSource(holding), source: "holding", classification: classifyDepotProduct(holding) };
}
const contract: BondPriceInput = {
  nominal: 10000, clean: 98, accrued: 200, market: 10000, fxRate: 1, bondCurrency: "EUR", valuationDate: "2026-01-01",
  units: { clean: "percent-of-par", nominal: "face-in-bond-currency", accrued: "absolute", accruedCurrency: "bond", market: "dirty-absolute", reportingCurrency: "EUR", fx: "reporting-per-bond" },
  quality: "documented", accruedQuantizationPer100: 0.0001,
};

// Constants independently generated by scripts/bond-v2-reference.py (Decimal70,
// Newton in y), never obtained from the production calendar or solver.
test("independent solver constants, residuals and duration", () => {
  const cases: [number, number[][], number, number, number][] = [
    [100, [[105, 365]], .05, 1, .9523809523809524],
    [100, [[105, 366]], .04986003754670353, 1.0027397260273974, .9551175301143796],
    [100, [[5, 1], [105, 366]], .10494510800400492, .9527533947967481, .8622631005786532],
    [100, [[2.5, 181], [102.5, 365]], .05063026595778512, .9877021791036884, .9401044412167875],
    [90, [[100, 730]], .05409255338945978, 2, 1.8973665961010275],
    [105, [[100, 365]], -.047619047619047616, 1, 1.05],
    [105, [[105, 365]], 0, 1, 1],
    [100.1, [[100, 5]], -.07036526152883343, 5 / 365, .01473549725509873],
    [102.93118208, [[103, 5]], .05000000261429889, 5 / 365, .013046314383694606],
    [102.93118208, [[106, 5]], 7.538863301534818, 5 / 365, .0016042685839137442],
  ];
  for (const [price, dates, yieldExpected, mac, mod] of cases) {
    const flows = dates.map(([amount, days]) => ({ amount, time: days / 365 }));
    const solved = solveBondYield(price, flows)!;
    close(solved?.value, yieldExpected);
    assert.ok(solved.iterations <= 200);
    assert.ok(Math.abs(solved.residual) <= Math.max(1e-8, 1e-10 * price));
    // Independent ordinary power PV; no production pricing helper as oracle.
    const pv = (y: number) => dates.reduce((sum, [a, d]) => sum + a / (1 + y) ** (d / 365), 0);
    close(pv(solved.value), price, 1e-8);
    const duration = datedBondDuration(price, flows, solved.value)!;
    close(duration.macaulay, mac, 1e-8); close(duration.modified, mod, 1e-8);
    const h = Math.min(1e-4, (1 + solved.value) / 4);
    const fd = (pv(solved.value - h) - pv(solved.value + h)) / (2 * h * price);
    close(fd * 100000 * .0001, mod * 10, .01);
  }
  close(datedBondDuration(100, [{ amount: 2.5, time: 181 / 365 }, { amount: 102.5, time: 1 }], .05063026595778512)!.modified * 10, 9.401044412167875);
});
test("extreme positive, negative, near-minus-one and technical failures", () => {
  close(solveBondYield(16, [{ amount: 105, time: 1 }])?.value, 5.5625);
  close(solveBondYield(1e-8, [{ amount: 100, time: 1 }])?.value, 9999999999, .1);
  close(solveBondYield(100, [{ amount: .001, time: 1 }])?.value, -.99999, 1e-10);
  const y = -.99999, h = Math.min(1e-9, (1 + y) / 4);
  const fd = ((.001 / (1 + y - h)) - (.001 / (1 + y + h))) / (2 * h * 100);
  close(fd, 100000, .01);
  for (const p of [0, -1, NaN, Infinity]) assert.equal(solveBondYield(p, [{ amount: 100, time: 1 }]), null);
  for (const cf of [[], [{ amount: -1, time: 1 }], [{ amount: 1, time: 0 }], [{ amount: Infinity, time: 1 }]]) assert.equal(solveBondYield(100, cf), null);
  assert.equal(solveBondYield(1, [{ amount: 100, time: 1e-9 }]), null);
  assert.equal(bondPresentValue([{ amount: 100, time: 1000 }], -.99), null);
  assert.equal(datedBondDuration(99, [{ amount: 105, time: 1 }], .05), null);
});
test("annual calendar distinct from the 366-day pure solver", () => {
  const c = annualBondCalendar("2026-01-01", "2027-01-02", 5)!;
  assert.deepEqual(c.cashflows.map(({ date, amount }) => [date, amount]), [["2026-01-02", 5], ["2027-01-02", 105]]);
  close(solveBondYield(100, c.cashflows)?.value, .10494510800400492);
  assert.equal(annualBondCalendar("2026-01-01", "2027-01-01", 5)!.cashflows.length, 1);
  assert.equal(annualBondCalendar("2026-01-01", "2026-01-01", 5), null);
  assert.equal(annualBondCalendar("2026-02-30", "2027-01-01", 5), null);
});
test("original EOM anchor, leap years and non-EOM dates without drift", () => {
  const c = annualBondCalendar("2023-01-01", "2028-02-29", 5)!;
  assert.deepEqual(c.cashflows.map((cf) => cf.date), ["2023-02-28", "2024-02-29", "2025-02-28", "2026-02-28", "2027-02-28", "2028-02-29"]);
  assert.equal(annualBondCalendar("2023-03-01", "2025-02-28", 5)!.cashflows[0].date, "2024-02-29");
  assert.equal(annualBondCalendar("2023-03-01", "2025-02-27", 5)!.cashflows[0].date, "2024-02-27");
});
test("all five mandatory absolute AI / FX price fixtures", () => {
  close(resolveBondPrice(contract).dirty.value, 100);
  for (const [fx, direction, ai, aiCurrency, market] of [
    [.9, "reporting-per-bond", 200, "bond", 9000], [.9, "reporting-per-bond", 180, "reporting", 9000],
    [1.25, "bond-per-reporting", 200, "bond", 8000], [1.25, "bond-per-reporting", 160, "reporting", 8000],
  ] as const) {
    const price = resolveBondPrice({ ...contract, bondCurrency: "USD", fxRate: fx, accrued: ai, market, units: { ...contract.units, accruedCurrency: aiCurrency, fx: direction } });
    close(price.dirty.value, 100); close(price.localDirtyValue, 10000); assert.equal(price.currency, "USD");
  }
});
test("absolute AI2 is not 2 points; dirty total never receives AI twice", () => {
  close(resolveBondPrice({ ...contract, accrued: 2, market: 9802 }).dirty.value, 98.02);
  close(resolveBondPrice({ ...contract, accrued: undefined }).dirty.value, 100);
  assert.equal(resolveBondPrice({ ...contract, market: 9800 }).dirty.reasonCode, "price-path-conflict");
  assert.equal(resolveBondPrice({ ...contract, market: 0 }).dirty.reasonCode, "price-path-conflict");
  assert.equal(resolveBondPrice({ ...contract, fxRate: 1.25 }).dirty.reasonCode, "currency-fx-conflict");
});
test("no per-row FX / AI reinterpretation and no majority proof", () => {
  const foreign = { ...contract, bondCurrency: "USD", market: 9000, fxRate: .9 };
  assert.equal(resolveBondPrice({ ...foreign, units: { ...contract.units, fx: "unknown" } }).dirty.value, null);
  assert.equal(resolveBondPrice({ ...foreign, units: { ...contract.units, accruedCurrency: "unknown" } }).dirty.value, null);
  const ambiguous = resolveBondPrice({ ...contract, nominal: 100, accrued: 2, market: 100, quality: "profile-assumption", units: { ...contract.units, fx: "unknown", accruedCurrency: "unknown" } });
  close(ambiguous.dirty.value, 100); assert.equal(ambiguous.quality, "profile-assumption");
  const nearOne = resolveBondPrice({ ...foreign, fxRate: 1.00001, units: { ...contract.units, fx: "unknown" } });
  assert.equal(nearOne.dirty.value, null); // Source tolerance is NOT invariance.
});
test("independent local price without nominal or EUR, dates and unknown currency", () => {
  const local = resolveBondPrice({ ...contract, nominal: undefined, market: undefined, accrued: 2, fxRate: undefined, bondCurrency: "USD", units: { ...contract.units, accrued: "per100", reportingCurrency: null } });
  close(local.dirty.value, 100); assert.equal(local.localDirtyValue, null);
  assert.equal(resolveBondPrice({ ...contract, nominal: undefined }).dirty.value, null);
  assert.equal(resolveBondPrice({ ...contract, valuationDate: undefined }).dirty.value, null);
  for (const key of ["priceDate", "accruedDate", "fxDate"]) assert.equal(resolveBondPrice({ ...contract, [key]: "2026-01-02" }).dirty.reasonCode, "valuation-date-conflict");
  assert.equal(resolveBondPrice({ ...contract, bondCurrency: undefined }).dirty.value, null);
  close(resolveBondPrice({ ...contract, bondCurrency: "USD", accrued: 1.8, market: 9000, fxRate: .9,
    units: { ...contract.units, accrued: "per100", accruedCurrency: "reporting" } }).dirty.value, 100);
});
test("annual-model contradiction, three daycounts, source rounding and ex coupon", () => {
  assert.equal(annualAccruedCheck("2026-12-27", "2027-01-01", 6, 2.9185, .0001), "annual-model-contradiction");
  assert.equal(annualAccruedCheck("2026-12-27", "2027-01-01", 6, 6 * 360 / 365, .0001), "compatible");
  assert.equal(annualAccruedCheck("2026-12-27", "2027-01-01", 6, 2.9185, null), "not-testable");
  assert.equal(annualAccruedCheck("2026-12-27", "2027-01-01", 6, null, .0001), "not-testable");
  assert.equal(annualAccruedCheck("2026-01-01", "2027-01-01", 6, .1, null), "ex-coupon-unclear");
  assert.equal(annualAccruedCheck("2026-02-01", "2027-01-01", 6, -.1, null), "ex-coupon-unclear");
  // 30E/360 matches while ACT variants need not be the closest interpretation.
  assert.equal(annualAccruedCheck("2026-04-30", "2027-01-31", 12, 3, .0001), "compatible");
  assert.equal(annualAccruedCheck("2026-01-02", "2027-01-01", 0, .051, 0), "annual-model-contradiction");
  assert.equal(annualAccruedCheck("2026-01-02", "2027-01-01", 0, .051, .026), "compatible");
  const documentedPrice = resolveBondPrice({ ...contract, valuationDate: "2026-12-27", clean: 100.01268208, accrued: 291.85, market: 10293.118208 });
  const result = calculateBondModel(documentedPrice, "2026-12-27", "2027-01-01", 6);
  assert.equal(result.ytm.reasonCode, "annual-model-contradiction");
  for (const m of [result.ytm, result.macaulay, result.modified, result.dv01]) assert.equal(m.value, null);
});
test("2.25 percent short bond: independent dirty yield and AI variation", () => {
  const ai = 2.25 * 336 / 365;
  const dirty = 99.885 + ai;
  close(solveBondYield(dirty, [{ amount: 102.25, time: 29 / 365 }])?.value, .036876232786203627);
  assert.equal(annualAccruedCheck("2026-09-09", "2026-10-08", 2.25, ai, .0001), "compatible");
  assert.equal(annualAccruedCheck("2026-09-09", "2026-10-08", 2.25, 0, .0001), "annual-model-contradiction");
  assert.equal(resolveBondPrice({ ...contract, nominal: undefined, accrued: undefined, clean: 99.885 }).dirty.value, null);
});
test("CSV zero-touch individual metrics, provenance, local DV01", () => {
  const row = imported(); const result = analyzeBondV2(row);
  close(result.ytm.value, .05); close(result.currentYield.value, .05);
  close(result.macaulay.value, 1); close(result.modified.value, 1 / 1.05);
  close(result.dv01.value, .9523809523809524); assert.equal(result.dv01Currency, "EUR");
  assert.equal(result.sourceQuality, "profile-assumption"); assert.equal(result.reportingComparable, false);
  assert.equal(result.annualCheck, "not-testable");
  assert.ok(result.warnings.includes("Kuponmodell nicht prüfbar"));
  assert.deepEqual(analyzeBondV2(JSON.parse(JSON.stringify(row))), result);
  const usd = analyzeBondV2(imported({ currency: "USD" }));
  close(usd.ytm.value, .05); assert.equal(usd.dv01Currency, "USD");
});
test("different prerequisites, missing AI and no maturity/FX blanket exclusion", () => {
  close(analyzeBondV2(imported({ accruedInterest: undefined })).ytm.value, .05);
  const noMaturity = analyzeBondV2(imported({ maturity: undefined }));
  close(noMaturity.currentYield.value, .05); assert.equal(noMaturity.ytm.value, null);
  const missingCoupon = analyzeBondV2(imported({ coupon: undefined }));
  close(missingCoupon.remainingYears.value, 1); assert.equal(missingCoupon.currentYield.value, null);
  const noDate = analyzeBondV2(imported({ valuationEnd: undefined }), new Date(2026, 0, 1));
  close(noDate.remainingYears.value, 1); assert.equal(noDate.ytm.value, null); close(noDate.currentYield.value, .05);
  assert.ok(noDate.warnings.some((w) => w.includes("Fallback")));
  const old = analyzeBondV2({ ...imported(), bondSource: undefined });
  assert.equal(old.ytm.status, "legacy-unverified"); close(old.remainingYears.value, 1);
  const noNominal = analyzeBondV2(imported({ nominalOrUnits: undefined }));
  assert.equal(noNominal.ytm.value, null); close(noNominal.currentYield.value, .05);
});
test("changed position amount cannot reuse a stale absolute DV01", () => {
  const original = imported();
  const changed = analyzeBondV2({ ...original, value: 5000 });
  close(changed.ytm.value, .05); // Independent clean plus explicit AI0 is unchanged.
  assert.equal(changed.dv01.value, null);
  assert.equal(changed.dv01.reasonCode, "position-amount-changed");
});
test("explicit zero AI is currency-invariant even without FX", () => {
  close(analyzeBondV2(imported({ fxRate: undefined })).ytm.value, .05);
  assert.equal(analyzeBondV2(imported({ fxRate: undefined, accruedInterest: 200 })).ytm.value, null);
});
test("valid zero vs invalid coupon and positive legacy parser corruption", () => {
  close(analyzeBondV2(imported({ coupon: 0 })).ytm.value, 0);
  for (const raw of ["n/a", "5abc", "1e3", "NaN", "Infinity", "1.234"]) {
    const parsed = csv(`${header}\nSynthetisch;Festverzinsliche;;;EUR;${raw};01.01.2027;10000;100;10000;0;1;01.01.2026`).rows[0];
    const result = analyzeBondV2({ ...parsed, source: "holding", classification: classifyDepotProduct(parsed) });
    assert.equal(result.ytm.value, null); assert.equal(result.currentYield.value, null);
    assert.equal(parsed.bondSource!.fields.coupon.status, "invalid");
  }
  for (const coupon of [0, 5, 13]) assert.equal(analyzeBondV2({ ...imported({ coupon }), bondSource: undefined }).ytm.status, "legacy-unverified");
});
test("source changes cannot reuse old evidence, malformed profile degrades locally", () => {
  const source = imported();
  assert.equal(analyzeBondV2({ ...source, coupon: 6 }).ytm.value, null);
  assert.equal(analyzeBondV2({ ...source, name: "Changed" }).ytm.value, null);
  assert.equal(validBondSource({ ...source.bondSource, profileVersion: 999 }, source), undefined);
  assert.equal(validBondSource({ ...source.bondSource, units: null }, source), undefined);
  assert.equal(validBondSource({ ...source.bondSource, quality: "documented" }, source), undefined);
});
test("unsupported structures, maturity, zero price, negative AI and extreme yield", () => {
  for (const kind of ["Floater", "Step-up", "Callable", "Convertible", "Rentenfonds", "Zertifikat", "Festverzinsliche Default", "Festverzinsliche Inflation-linked"]) {
    const result = analyzeBondV2(imported({ investmentMedium: kind }));
    assert.equal(result.ytm.value, null, kind);
  }
  close(analyzeBondV2(imported({ securityType: "Floater" })).currentYield.value, .05);
  assert.equal(analyzeBondV2(imported({ maturity: "2026-01-01" })).ytm.reasonCode, "matured");
  assert.equal(analyzeBondV2(imported({ maturity: "2025-01-01" })).ytm.value, null);
  assert.equal(analyzeBondV2(imported({ value: 0, currentPrice: 0 })).ytm.value, null);
  assert.equal(analyzeBondV2(imported({ accruedInterest: -1 })).ytm.value, null);
  close(analyzeBondV2(imported({ currentPrice: 16, value: 1600 })).ytm.value, 5.5625);
  for (const extra of [{ sourceType: "Inflation-linked" }, { certificateClass: "Payment delay" }])
    assert.equal(analyzeBondV2(imported(extra)).ytm.reasonCode, "special-payment-conditions");
});
test("5-day rounding sensitivity is visible and never a high-yield filter", () => {
  const a = analyzeBondV2(imported({ coupon: 0, valuationEnd: "2026-12-27" }));
  const b = analyzeBondV2(imported({ coupon: 0, valuationEnd: "2026-12-27", value: 10010, currentPrice: 100.1 }));
  close(a.ytm.value, 0); close(b.ytm.value, -.07036526152883343);
  assert.ok(b.warnings.some((w) => w.includes("rundungssensitiv")));
  const high = analyzeBondV2(imported({ coupon: 6, valuationEnd: "2026-12-27", value: 10293.118208, currentPrice: 102.93118208, accruedInterest: undefined }));
  close(high.ytm.value, 7.538863301534818); assert.equal(high.annualCheck, "not-testable");
});
test("schema 10 to 11, existing 11, JSON, save/load and snapshot restore", () => {
  let item = createCase();
  const row = imported();
  item = { ...item, ...addDepotAccount(item, [row], "Synthetisches Depot") };
  item.depot[0].excludeFromBondAggregates = true;
  const legacy = { ...item, schemaVersion: 10, depot: [...item.depot, { ...item.depot[0], id: "legacy", coupon: 0, bondSource: undefined, excludeFromBondAggregates: undefined }] };
  const original = JSON.stringify(legacy);
  const migrated = normalizeImportedCase(legacy, false)!;
  assert.equal(migrated.schemaVersion, 11); assert.equal(JSON.stringify(legacy), original);
  assert.equal(migrated.depot[0].excludeFromBondAggregates, true); assert.equal(migrated.depot[1].excludeFromBondAggregates, false);
  assert.equal(migrated.depot[1].coupon, 0); assert.equal(migrated.depot[1].bondSource, undefined);
  assert.deepEqual(normalizeImportedCase(JSON.parse(JSON.stringify(migrated)), false)!.depot, migrated.depot);
  assert.deepEqual(readCaseStore(JSON.stringify([migrated])).cases[0].depot, migrated.depot);
  const snapshot = caseSnapshot(migrated);
  assert.equal(snapshot.schemaVersion, 11);
  assert.deepEqual(normalizeImportedCase(snapshot, false)!.depot, migrated.depot);
  const history = { ...legacy, versions: [{ id: "old", snapshot: { ...snapshot, schemaVersion: 10 } }] };
  assert.equal((normalizeImportedCase(history, false)!.versions[0].snapshot as { schemaVersion: number }).schemaVersion, 10);
  assert.equal(normalizeImportedCase({ ...migrated, schemaVersion: 12 }, false), null);
  assert.equal(readCaseStore(JSON.stringify([{ ...migrated, id: "future", schemaVersion: 12 }, migrated])).cases.length, 1);
  const corrupt = normalizeImportedCase({ ...migrated, depot: [{ ...migrated.depot[0], bondSource: { fields: null } }] }, false)!;
  assert.equal(corrupt.depot[0].bondSource, undefined); assert.equal(corrupt.depot[0].value, 10000);
  assert.ok(!/"(ytm|modified|dv01)":/.test(JSON.stringify(snapshot)));
});
test("new CSV source replaces old provenance; exclusion does not erase individual result", () => {
  const row = imported({ wkn: "SYN001", excludeFromBondAggregates: true });
  close(analyzeBondV2(row).ytm.value, .05);
  const item = createCase(); const state = addDepotAccount(item, [row], "Synthetic");
  const next = replaceDepotAccount(state, state.depotAccounts[0].id, [imported({ id: row.id, wkn: "SYN001", coupon: 6 })]);
  assert.equal(next.depot[0].bondSource!.fields.coupon.value, 6);
  assert.equal(state.depot[0].bondSource!.fields.coupon.value, 5);
});
test("actual store writes preserve source, exclusion and recover corrupt profile originals", () => {
  const values = new Map<string, string>();
  const storage = { get length() { return values.size; }, key: (i: number) => [...values.keys()][i] ?? null,
    getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => { values.set(key, value); } };
  let item = createCase(); item = { ...item, ...addDepotAccount(item, [imported({ excludeFromBondAggregates: true })], "Synthetic") };
  writeCaseStore(storage, [item]);
  const loaded = readCaseStore(storage.getItem(CASE_STORAGE_KEY)).cases[0];
  assert.deepEqual(loaded.depot, JSON.parse(JSON.stringify(item.depot)));
  const original = JSON.stringify([{ ...item, depot: [{ ...item.depot[0], bondSource: { broken: true } }] }]);
  storage.setItem(CASE_STORAGE_KEY, original);
  const recovered = readCaseStore(original);
  assert.equal(recovered.cases.length, 1); assert.equal(recovered.recoveryNeeded, true);
  writeCaseStore(storage, recovered.cases);
  assert.ok(recoveryBackups(storage).some((backup) => backup.original === original));
});
test("178 synthetic CSV rows produce 80 YTMs without edits, no false EUR aggregate", () => {
  const rows = Array.from({ length: 178 }, (_, i) => `Synthetic ${i};${i >= 100 ? "Aktien" : i >= 80 && i < 90 ? "Floater" : "Festverzinsliche"};;;EUR;${i >= 90 && i < 100 ? "n/a" : i >= 80 && i < 90 ? 4 : 5};01.01.2027;10000;100;10000;0;1;01.01.2026`);
  const parsed = csv([header, ...rows].join("\n"));
  const item = createCase(), state = addDepotAccount(item, parsed.rows, "Synthetic");
  assert.equal(state.depot.reduce((sum, p) => sum + p.value, 0), 1780000);
  const result = bondPortfolioAnalysis(buildDepotAnalysisPositions(state.depot, state.plans[0], "ist"));
  assert.equal(result.directValue, 1000000);
  assert.equal(result.rows.filter((r) => r.ytm !== null).length, 80);
  assert.equal(result.rows.filter((r) => r.currentYield !== null).length, 90);
  for (const r of result.rows.filter((r) => r.ytm !== null)) { close(r.ytm, .05); close(r.modified, .9523809523809524); }
  assert.equal(result.averageModeledYtm, null); assert.equal(result.ytmCoverage, null); assert.equal(result.portfolioDv01, null);
  assert.ok(result.scenarios.every((scenario) => scenario.effect === null));
});
console.log(`Bond V2: ${count} test groups passed; independent Decimal70 references and finite differences checked.`);
